/*-
 * Copyright (c) 2018 Jonathan Anderson
 * All rights reserved.
 *
 * This software was developed at Memorial University under the
 * NSERC Discovery (RGPIN-2015-06048) and RDC Ignite (#5404.1822.101) programs.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#include <sys/capsicum.h>

#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>

#include "internal.h"

static bool	setup_linker(struct cs_sandbox *, const char *path);
static int	get_libdir(struct cs_sandbox *, const char *path,
			cap_rights_t *);

#define OPEN_LIBDIR(csp, i, path, rights) \
	do { \
		csp->libdirs[i] = get_libdir(csp, path, rights); \
		if (csp->libdirs[i] < 0) { \
			/* error message is generated by get_libdir */ \
			close(csp->linker); \
			for (int j = 0; j < i; j++) { \
				close(csp->libdirs[j]); \
			} \
			return (-1); \
		} \
	} \
	while (false)

bool
setup_compat32_libraries(struct cs_sandbox *csp)
{
	cap_rights_t libdir_rights;

	if (!setup_linker(csp, "/libexec/ld-elf32.so.1")) {
		return (false);
	}

	csp->libdir_count = 1;
	csp->libdirs = calloc(1, sizeof(csp->libdirs[0]));

	cap_rights_init(&libdir_rights, CAP_READ, CAP_MMAP, CAP_FEXECVE);
	OPEN_LIBDIR(csp, 0, "/usr/lib32", &libdir_rights);

	return (true);
}

bool
setup_linux_compat_libraries(struct cs_sandbox *csp)
{
	cap_rights_t libdir_rights;

	if (!setup_linker(csp, "/compat/linux/usr/lib/ld-linux.so.2")) {
		return (false);
	}

	csp->libdir_count = 1;
	csp->libdirs = calloc(1, sizeof(csp->libdirs[0]));

	cap_rights_init(&libdir_rights, CAP_READ, CAP_MMAP, CAP_FEXECVE);
	OPEN_LIBDIR(csp, 0, "/compat/linux/usr/lib", &libdir_rights);

	return (true);
}

bool
setup_native_libraries(struct cs_sandbox *csp)
{
	cap_rights_t libdir_rights;

	if (!setup_linker(csp, "/libexec/ld-elf.so.1")) {
		return (false);
	}

	csp->libdir_count = 3;
	csp->libdirs = calloc(3, sizeof(csp->libdirs[0]));

	cap_rights_init(&libdir_rights, CAP_READ, CAP_MMAP, CAP_FEXECVE);
	OPEN_LIBDIR(csp, 0, "/lib", &libdir_rights);
	OPEN_LIBDIR(csp, 1, "/usr/lib", &libdir_rights);
	OPEN_LIBDIR(csp, 2, "/usr/local/lib", &libdir_rights);

	return (true);
}

static bool
setup_linker(struct cs_sandbox *csp, const char *path)
{
	cap_rights_t rights;

	csp->linker = open(path, O_RDONLY);
	if (csp->linker < 0) {
		error_append(csp, "Failed to open run-time linker %s: %s",
			path, strerror(errno));
		return (false);
	}

	cap_rights_init(&rights, CAP_READ, CAP_MMAP, CAP_FEXECVE);
	if (cap_rights_limit(csp->linker, &rights) < 0) {
		error_append(csp, "Failed to restrict run-time linker %s: %s",
			path, strerror(errno));

		close(csp->linker);
		return (false);
	}

	return (true);
}

static int
get_libdir(struct cs_sandbox *csp, const char *path, cap_rights_t *rights)
{
	int fd;

	fd = open(path, O_RDONLY);
	if (fd < 0) {
		error_append(csp, "Failed to open library directory %s: %s",
			path, strerror(errno));
		return (-1);
	}

	if (cap_rights_limit(fd, rights) < 0) {
		error_append(csp, "Failed to restrict library directory %s: %s",
			path, strerror(errno));
		close(fd);
		return (-1);
	}

	return (fd);
}
